#!/usr/bin/env python3
"""Zero-dependency smoke client for a running AutoFTBQ MCP instance."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from urllib.request import Request, urlopen
from urllib.error import HTTPError


PROTOCOL = "2026-07-28"


def load_runtime(path: Path) -> tuple[str, str]:
    value = json.loads(path.read_text(encoding="utf-8"))
    return str(value["url"]), str(value["token"])


def rpc(url: str, token: str, method: str, params: dict | None = None, *, name: str | None = None):
    body = {
        "jsonrpc": "2.0",
        "id": 1,
        "method": method,
        "params": params or {},
    }
    headers = {
        "Authorization": f"Bearer {token}",
        "Content-Type": "application/json",
        "Accept": "application/json",
        "MCP-Protocol-Version": PROTOCOL,
        "Mcp-Method": method,
    }
    if name is not None:
        headers["Mcp-Name"] = name

    request = Request(
        url,
        data=json.dumps(body).encode("utf-8"),
        headers=headers,
        method="POST",
    )
    try:
        with urlopen(request, timeout=10) as response:
            return json.loads(response.read().decode("utf-8"))
    except HTTPError as exc:
        payload = exc.read().decode("utf-8", errors="replace")
        raise SystemExit(f"HTTP {exc.code}: {payload}") from exc


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--runtime",
        type=Path,
        default=Path("config/autoftbq-mcp/runtime.json"),
        help="Path to the runtime credential file generated by the mod",
    )
    parser.add_argument(
        "--call-health-tool",
        action="store_true",
        help="Also call autoftbq.health (requires a loaded/connected game for full results)",
    )
    args = parser.parse_args()

    url, token = load_runtime(args.runtime)

    discovered = rpc(url, token, "server/discover")
    versions = discovered.get("result", {}).get("supportedVersions", [])
    if PROTOCOL not in versions:
        raise SystemExit(f"server/discover did not advertise {PROTOCOL}: {versions!r}")
    print(f"discover: ok ({', '.join(versions)})")

    listed = rpc(url, token, "tools/list")
    tools = listed.get("result", {}).get("tools", [])
    names = {tool.get("name") for tool in tools}
    required = {
        "autoftbq.health",
        "minecraft.search_registry",
        "ftbq.get_book",
        "ftbq.create_quest",
        "ftbq.transaction_commit",
    }
    missing = required - names
    if missing:
        raise SystemExit(f"tools/list missing required tools: {sorted(missing)}")
    print(f"tools/list: ok ({len(tools)} tools)")

    if args.call_health_tool:
        health = rpc(
            url,
            token,
            "tools/call",
            {"name": "autoftbq.health", "arguments": {}},
            name="autoftbq.health",
        )
        result = health.get("result", {})
        if result.get("isError"):
            raise SystemExit(f"autoftbq.health returned an MCP tool error: {result}")
        print("autoftbq.health: ok")
        print(json.dumps(result.get("structuredContent", {}), indent=2, ensure_ascii=False))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
